server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /control-citas

spring:
  application:
    name: control-citas
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/control_citas
    username: test
    password: "contraseña1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    discovery:
      enabled: true
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        default-zone: http://localhost:8761/eureka
      instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}